### ISSUE TITLE
CMake build issue with react native 0.76

### ISSUE THREAD

**Issue by Ruslan-Mz** [margelo/react-native-nitro-sqlite#72]
Hi!

After updating to react native 0.76 (but with new architecture disabled) I have a build issues using Quick SQL lite on android (on iOS everything is ok):
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-quick-sqlite:configureCMakeDebug[arm64-v8a]'.
	at [........]
Caused by: com.android.builder.errors.EvalIssueException: [CXX1429] error when building with cmake using [...]/node_modules/react-native-quick-sqlite/android/CMakeLists.txt: -- The C compiler identification is Clang 18.0.3

CMake Error at CMakeLists.txt:23 (add_library):
  Target "RNQuickSQLite" links to target "ReactAndroid::turbomodulejsijni"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:23 (add_library):
  Target "RNQuickSQLite" links to target
  "ReactAndroid::react_nativemodule_core" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

can you please check?

**Comment by alzalabany** [comment]
any news ? thanks so much for you hard work

**Comment by Ruslan-Mz** [comment]
Probably this is the reason and guide to fix that: https://github.com/react-native-community/discussions-and-proposals/discussions/816

**Comment by chrispader** [comment]
This should be fixed in https://github.com/margelo/react-native-quick-sqlite/releases/tag/v8.2.3

Thanks @Ruslan-Mz for pointing out the issue! ❤️

**Comment by Anass001** [comment]
Still facing the same issue on v8.2.3

**Comment by chrispader** [comment]
> Still facing the same issue on v8.2.3

Did you clean your android files after upgrading? `Clean build folder` in Android Studio or optimally `git clean -Xdf`

**Comment by LydGol90** [comment]
@chrispader @Anass001 I am also still seeing the issue on 8.2.3 and I have cleaned everything. New arch disabled. Many thanks

**Comment by hassanimtiaz26** [comment]
@chrispader I am also facing this issue. I Cleaned and rebuilt the project in Android Studio but still facing this issue.

**Comment by smfunder** [comment]
hello @chrispader yes, I'm facing same issue on react native 0.76.1 + New Arch Enabled when building in Android. If I can provide more information please let me know. I have the full log. Also I did a ./gradlew clean before building android.

I also ran the:
git clean -Xdf
./gradlew clean

So everything seems to be clean.

**Comment by smfunder** [comment]
Please consider opening this Issue again. 
I was able to make it build by replacing the CMakeLists.txt file with the following content:

> project(RNQuickSQLite)
> cmake_minimum_required(VERSION 3.9.0)
> 
> set (PACKAGE_NAME "RNQuickSQLite")
> set (CMAKE_VERBOSE_MAKEFILE ON)
> set (CMAKE_CXX_STANDARD 17)
> set (BUILD_DIR ${CMAKE_SOURCE_DIR}/build)
> 
> include_directories(
>   ../cpp
> )
> 
> add_definitions(
>   ${SQLITE_FLAGS}
> )
> 
> file(GLOB_RECURSE cpp_files RELATIVE ${CMAKE_SOURCE_DIR}
>   "../cpp/**.c"
>   "../cpp/**.cpp"
>   "src/main/cpp/cpp-adapter.cpp"
> )
> 
> find_package(ReactAndroid REQUIRED CONFIG)
> find_package(fbjni REQUIRED CONFIG)
> find_library(LOG_LIB log)
> 
> add_library(${PACKAGE_NAME} SHARED
>   ${cpp_files}
> )
> 
> set_target_properties(
>   ${PACKAGE_NAME} PROPERTIES
>   CXX_STANDARD 17
>   CXX_EXTENSIONS OFF
>   POSITION_INDEPENDENT_CODE ON
> )
> 
> target_link_libraries(
>   ${PACKAGE_NAME}
>   ${LOG_LIB}
>   fbjni::fbjni
>   ReactAndroid::jsi
>   ReactAndroid::reactnative
>   android
> )
> 

Basically I'm changing the taget_link_libraries with `ReactNative::reactnative` instead of `ReactNative::turbomodulejsijni` and `ReactAndroid::react_nativemodule_core`

Because in React Native 0.76 here they detail that those libraries were merged into ReactNative::reactnative : https://github.com/react-native-community/discussions-and-proposals/discussions/816

But still I'm getting a running issue as detailed in this screenshot which seems to be reported here: https://github.com/margelo/react-native-quick-sqlite/issues/48

![WhatsApp Image 2024-11-10 at 17 44 46](https://github.com/user-attachments/assets/779eaa38-f825-47be-bbe0-391f84d39e36)

**Comment by chrispader** [comment]
This should now be fixed for real 😅 

https://github.com/margelo/react-native-quick-sqlite/releases/tag/v8.2.4
